name: "PR Tasks Completed Check"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for incomplete task items
        uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
